name: Build

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  ci-build:
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - name: Windows
          os: windows-latest
          target: windows
          runtime: win-x64
          artifact: FamilyAlbumDownloader.exe

        - name: Linux
          os: ubuntu-latest
          target: linux
          runtime: linux-x64
          artifact: FamilyAlbumDownloader

        - name: Mac
          os: macos-latest
          target: mac
          runtime: osx-x64
          artifact: FamilyAlbumDownloader


    name: ${{ matrix.cfg.name }} ${{ github.ref }}
    runs-on: ${{ matrix.cfg.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - run: cargo build --release --all-features
    - run: cargo test --release --all-features
    - uses: actions/upload-artifact@v4
      with:
        name: FamilyAlbumDownloader-${{ matrix.cfg.runtime }}
        path: target/release/${{ matrix.cfg.artifact }}
